#!/usr/bin/with-contenv sh
set -e -u -o pipefail
if [ ! -r ${OC_CFG} ]; then
  echo "Could not load config file from /vpn/vpn.config. Please check your volume config" 1>&2
  exit 1
fi

source ${OC_CFG}

if [ -z "${HTTP_PROXY_PORT}" ]; then
  echo "HTTP proxy is not enabled"
  sleep infinity
fi

while ! $(ip link | grep -q tun0); do sleep 1; done
echo "Privoxy: Openconnect is running"

echo "Starting privoxy on port ${HTTP_PROXY_PORT}"
privoxy --no-daemon /etc/privoxy/config 