#!/usr/bin/with-contenv bash
set -e -u -o pipefail

if [ ! -r ${OC_CFG} ]; then
  echo "Could not load config file from /vpn/vpn.config. Please check your volume config" 1>&2
  exit 1
fi

source ${OC_CFG}

if [ -z "$SERVER" ]; then
  echo "No server is set. Exiting."
  exit 1
fi

if [ -z "$USERNAME" ]; then
  echo "No username is set. Exiting."
  exit 1
fi

if [ -z "$PASSWORD" ]; then
  echo "No password is set. Exiting."
  exit 1
fi

echo "Reading token..."
read TOKEN < /vpn/token
while [ -z ${TOKEN} ]; do
  sleep 1;
  read TOKEN < /vpn/token;
done
echo "Token provided as ${TOKEN}"

if [ ${DYNAMIC_TOKEN} = true ]; then
  echo "Resetting token for next use..."
  echo "" > /vpn/token
fi

echo "Starting openconnect..."
(
  echo -e "${PASSWORD}\n${TOKEN}"
  read -s
) | openconnect ${SERVER} --pid-file=${OC_PID} --user=${USERNAME} --passwd-on-stdin

sleep infinity &

wait
