#!/usr/bin/with-contenv sh
set -e -u -o pipefail

while ! $(ip link | grep -q tun0); do sleep 1; done
echo "Keepalive: Openconnect is running"

source ${OC_CFG}

if [ -z "$KEEP_ALIVE_ENDPOINT" ]; then
  echo "No keep alive endpoint server is set. Exiting."
  exit 1
fi

while :; do
  ping -i 10 -q ${KEEP_ALIVE_ENDPOINT}
done

