#!/bin/bash
if [ ! -r /vpn/vpn.config ] ; then
        echo "Could not load config file from /vpn/vpn.config. Please check your volume config" 1>&2
        exit 1
fi

source /vpn/vpn.config


if [ -z "$SERVER" ]; then
  echo "No server is set. Exiting."
  exit 1
fi

if [ -z "$USERNAME" ]; then
  echo "No username is set. Exiting."
  exit 1 
fi

if [ -z "$PASSWORD1" ]; then
  echo "No password1 is set. Exiting."
  exit 1
fi

if [ -z "$PASSWORD2" ]; then
  echo "No password2 is set. Exiting."
  exit 1
fi

if [ -z "${PROXY_PORT}" ]; then
  echo "No port is set, exiting"
  exit 1
fi

# so return traffic that went through VPN works
gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NETWORK} via $gw dev eth0

echo Running openconnect
(echo -e "${PASSWORD1}\n${PASSWORD2}"; read -s) | openconnect ${SERVER} --passwd-on-stdin --no-dtls -b -u ${USERNAME}
sleep 3

# start
if [[ -n "$SUSERNAME" -a -n "$SPASSWORD" ]]; then
  echo "Running brook with authentication"
  brook socks5 --socks5 0.0.0.0:${PROXY_PORT} --username ${SUSERNAME} --password ${SPASSWORD} &> /dev/null
else
  echo "Running brook without authentication"
  brook socks5 --socks5 0.0.0.0:${PROXY_PORT} &> /dev/null
fi
