#!/command/with-contenv sh
set -e -u -o pipefail

while ! $(ip link | grep -q tun0); do sleep 1; done

echo "Adding route to ${LOCAL_NETWORK} via ${DEFAULT_GW}"
ip route add ${LOCAL_NETWORK} via ${DEFAULT_GW} dev eth0

echo "Starting 3proxy..."
3proxy /etc/3proxy/3proxy.cfg