#!/usr/bin/with-contenv sh
echo -e "/var/run/openconnect.pid" >/var/run/s6/container_environment/OC_PID

gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NETWORK} via $gw dev eth0

if [ ! -f /etc/3proxy/updated ]; then
  if [ -n "${PROXY_USER}" ] && [ -n "${PROXY_PASS}" ]; then
    echo "Set proxy username and password"
    echo "users ${PROXY_USER}:CL:${PROXY_PASS}" >>/etc/3proxy/cfg/3proxy.cfg
    echo "auth strong" >>/etc/3proxy/3proxy.cfg
  else
    echo "Set proxy without username and password"
  fi

  echo "proxy -p${HTTP_PROXY_PORT} -Detun0" >>/etc/3proxy/3proxy.cfg
  echo "socks -p${PROXY_PORT} -Detun0" >>/etc/3proxy/3proxy.cfg
  echo "flush" >>/etc/3proxy/3proxy.cfg
  touch /etc/3proxy/updated
fi
